Feature/arraybuffer-broadcast
allen-cell-animated/simularium-engine pull request #8
Opened 2020-12-11 03:15 UTC by EricJIsaac

**Pull request recommendations:**

- [ ] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [ ] Link to any relevant issue in the PR description. Ex: _Resolves [gh-##], adds tiff file format support_
- [ ] Provide description and context of changes.
- [ ] Provide relevant tests for your feature or bug fix.
- [ ] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

Satisfies https://aicsjira.corp.alleninstitute.org/browse/AGENTVIZ-1124 & https://aicsjira.corp.alleninstitute.org/browse/AGENTVIZ-636

I still recommend that we wait to merge this until after chasing down bugs for the first release, but do think this is a large change and it would be good to get eyes on it sooner than later.

Implements binary file encoding & broadcasting for trajectory data. After this update, the simularium-engine backend will processed downloaded trajectories into the simularium binary format specified [here](https://docs.google.com/document/d/1Hdvw3XieGrTHd7swILzMXLY-dbu-auJVDvt9K1Zbb_Y/edit)

Also removes the ID_PLAY_CACHE netmessage identifier since it is no longer needed. The corresponding PR in the viewer also removes this message identifier.

The simularium_cache object also no longer deals directly w/ io streams, which hopefully should help the functionality there read easier (searing for alternate file names, downloading, and tracking converted files).

2020-12-16 08:30 UTC, heeler approved these changes
Your code style is really elegant. I'm wondering if creating structs with << and >> operators might make this code more portable assuming it needs to be on both the sending and receiving end of things. I'm personally a big fan of stl container and  stl algorithm style championed by Marshall Clow so that influences my comments.

2020-12-16 23:41 UTC, blairlyons requested changes
I just want to very clearly mark that this PR shouldn't be merged until after the release

2021-03-10 01:44 UTC, EricJIsaac commented on src/main/simularium_binary_file.cpp
> +        for (std::size_t j = 0; j < agentData.subpoints.size(); ++j) {
1. Its a nit-pick but the C++ specification didn't require all containers to implement auto iteration in order (last time I checked)
2. That is correct - in practice most machines that have actually run this (x86 general-purpose CPUs) have been little-endian
3. I think this is a good idea, and will look at this in a future PR

2021-03-10 01:47 UTC, EricJIsaac commented
Re-opening this post the R1 release. Time was taken to test the change alongside updates that occurred Dec-Jan

2021-03-10 21:24 UTC, toloudis commented on inc/simularium/network/connection_manager.h
> +    const std::size_t eos = std::numeric_limits<std::size_t>::max();
The above info would be great to have in a comment preceding the variable declaration

2021-03-10 21:26 UTC, toloudis commented on inc/simularium/simulation.h
> +	*	CacheAgents
indenting seems messed up here too

2021-03-10 22:16 UTC, EricJIsaac commented on src/main/connection_manager.cpp
> +            LOG_F(ERROR, "No net state for client %s", connectionUID.c_str());
This should be handled properly in the most recent commit - the clients are marked for removal and removed alongside expired connections (previously invalid/erroring clients were removed when discovered invalid, including during transmission attempts)

2021-03-11 03:27 UTC, toloudis commented on src/main/simularium_binary_file.cpp
> +    this->m_fstream.write((char*)&header[0], header.size() * sizeof(unsigned char));
Suggestion: instead of sizeof(unsigned char) here you could use sizeof(header[0]) which may be slightly less error prone in that you don't have to have the type in two places.  This pattern comes up a lot.

2021-03-22 17:35 UTC, blairlyons approved these changes

2021-03-22 18:21 UTC, toloudis commented on src/main/simularium_binary_file.cpp
> +    int tocPos = fileio::binary::TOC_ENTRY_COUNT_OFFSET + nFrames * 4;
This one changed? Should it be 16 or 20?

2021-03-23 17:03 UTC, EricJIsaac commented on src/main/simularium_binary_file.cpp
> +    int tocPos = fileio::binary::TOC_ENTRY_COUNT_OFFSET + nFrames * 4;
20, 16 bits for the header + 4 for the 'number of entries' entry

2021-03-23 21:21 UTC, toloudis commented on src/main/simularium_binary_file.cpp
> +    int tocPos = fileio::binary::TOC_ENTRY_COUNT_OFFSET + nFrames * 4;
What I'm seeing is the old code shows 20 + nFrames * 4 and the new code shows TOC_ENTRY_COUNT_OFFSET(==16) + nFrames * 4.   Does the code still work with this change?

2021-03-23 21:29 UTC, EricJIsaac commented on src/main/simularium_binary_file.cpp
> +    int tocPos = fileio::binary::TOC_ENTRY_COUNT_OFFSET + nFrames * 4;
Just pushed a correction

2021-03-23 21:33 UTC, toloudis commented on src/main/simularium_binary_file.cpp
> +    this->m_fstream.write((char*)fileio::binary::eof, sizeof(unsigned char) * 20);
Pretty sure you can replace the `sizeof(unsigned char)*20` with `sizeof(fileio::binary::eof)`

2021-03-25 21:32 UTC, merged